export const INITIAL_ROLES = [
  'ADMINISTRATOR',
  'OPERATIONS_MANAGER',
  'TERMINAL_MANAGER',
  'SUPERVISOR',
  'DISPATCHER',
  'DOCK_LEAD',
  'FORKLIFT_OPERATOR',
  'DRIVER',
  'VIEWER',
] as const;
