packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': set this to true or false
  '@prisma/engines': true
  '@scarf/scarf': set this to true or false
  prisma: true
  unrs-resolver: true
