import { type ReactNode } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ErrorState, LoadingState } from '../components/ui/ViewStates';
import { useDashboardSummary, useOperationalAssets } from '../hooks/useDashboard';
const colors = ['#2563eb','#7c3aed','#0d9488','#d97706','#e11d48'];
const label = (v:string) => v.replace(/([A-Z])/g,' $1').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const rows = (data:Record<string,number>) => Object.entries(data).map(([name,value])=>({name:label(name),value}));
export function AnalyticsPage(){
 const summary=useDashboardSummary(), assets=useOperationalAssets();
 if(summary.isLoading||assets.isLoading)return <LoadingState/>;
 if(summary.isError||assets.isError||!summary.data||!assets.data)return <ErrorState message="Could not build operational analytics."/>;
 const loaded=assets.data.containers.filter(c=>c.packageCount>0).length, moving=assets.data.trailers.filter(t=>t.status==='IN_TRANSIT').length, total=Object.values(summary.data.packages).reduce((a,b)=>a+b,0);
 const utilization=[{name:'Containers assigned',value:assets.data.containers.filter(c=>c.assignedTrailer).length},{name:'Containers unassigned',value:assets.data.containers.filter(c=>!c.assignedTrailer).length},{name:'Trailers carrying freight',value:assets.data.trailers.filter(t=>t.packageCount>0||t.containerCount>0).length},{name:'Empty trailers',value:assets.data.trailers.filter(t=>!t.packageCount&&!t.containerCount).length}];
 return <div className="mx-auto max-w-7xl space-y-7"><div><h2 className="text-2xl font-semibold text-slate-900">Operational analytics</h2><p className="mt-2 text-slate-500">Current distribution and utilization derived from live operational data.</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Delivery completion" value={`${total?Math.round(summary.data.packages.delivered/total*100):0}%`} note={`${summary.data.packages.delivered} of ${total} tracked packages`}/><Metric label="Loaded container rate" value={`${assets.data.containers.length?Math.round(loaded/assets.data.containers.length*100):0}%`} note={`${loaded} carrying packages`}/><Metric label="Active trailer rate" value={`${assets.data.trailers.length?Math.round(moving/assets.data.trailers.length*100):0}%`} note={`${moving} currently in transit`}/></div><div className="grid gap-6 lg:grid-cols-2"><ChartCard title="Package status distribution"><ResponsiveContainer width="100%" height={280}><BarChart data={rows(summary.data.packages)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#2563eb" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Container and trailer utilization"><ResponsiveContainer width="100%" height={280}><BarChart data={utilization} layout="vertical" margin={{left:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={135} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="value" fill="#7c3aed" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Trailer status"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={rows(summary.data.trailers)} dataKey="value" nameKey="name" innerRadius={62} outerRadius={100} paddingAngle={3}>{rows(summary.data.trailers).map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Container status"><ResponsiveContainer width="100%" height={280}><BarChart data={rows(summary.data.containers)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#0d9488" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></ChartCard></div></div>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></section>}
function ChartCard({title,children}:{title:string;children:ReactNode}){return <section className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="mb-5 font-semibold text-slate-900">{title}</h3>{children}</section>}
