import { Activity, Box, Container, PackageCheck, Truck } from 'lucide-react';
import { EmptyState, ErrorState, LoadingState } from '../components/ui/ViewStates';
import { StatusBadge } from '../components/ui/StatusBadge';
import { useDashboardSummary, useRecentEvents } from '../hooks/useDashboard';

const total = (values: Record<string, number>) => Object.values(values).reduce((a, b) => a + b, 0);
const time = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
export function DashboardPage() {
  const summary = useDashboardSummary(); const events = useRecentEvents();
  if (summary.isLoading || events.isLoading) return <LoadingState/>;
  if (summary.isError || events.isError || !summary.data) return <ErrorState/>;
  const cards = [
    { label: 'Packages tracked', value: total(summary.data.packages), detail: `${summary.data.packages.delivered} delivered`, icon: PackageCheck, tone: 'bg-sky-50 text-sky-700' },
    { label: 'Containers', value: total(summary.data.containers), detail: `${summary.data.containers.loaded} currently loaded`, icon: Container, tone: 'bg-violet-50 text-violet-700' },
    { label: 'Trailers', value: total(summary.data.trailers), detail: `${summary.data.trailers.inTransit} in transit`, icon: Truck, tone: 'bg-amber-50 text-amber-700' },
    { label: 'Recent events', value: events.data?.length ?? 0, detail: 'Latest network activity', icon: Activity, tone: 'bg-emerald-50 text-emerald-700' },
  ];
  return <div className="mx-auto max-w-7xl space-y-8"><div><h2 className="text-2xl font-semibold text-slate-900">Network at a glance</h2><p className="mt-2 text-slate-500">Live operational totals and the latest asset movements.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, detail, icon: Icon, tone }) => <section key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><div className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5"/></div><p className="mt-5 text-3xl font-semibold text-slate-900">{value.toLocaleString()}</p><p className="mt-1 text-sm font-medium text-slate-700">{label}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></section>)}</div><div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h3 className="font-semibold text-slate-900">Recent activity</h3></div>{events.data?.length ? <div className="divide-y">{events.data.slice(0, 10).map((event, i) => <div key={`${event.reference}-${i}`} className="flex items-center gap-4 px-6 py-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-50"><Box className="h-4 w-4 text-slate-500"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{event.reference}</p><p className="mt-0.5 text-xs text-slate-400">{time(event.occurredAt)}</p></div><StatusBadge value={event.event}/></div>)}</div> : <EmptyState label="No recent activity"/>}</section><section className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-semibold text-slate-900">Package flow</h3><div className="mt-6 space-y-5">{Object.entries(summary.data.packages).map(([label, value]) => { const max = Math.max(...Object.values(summary.data.packages), 1); return <div key={label}><div className="mb-2 flex justify-between text-sm"><span className="capitalize text-slate-600">{label.replace(/([A-Z])/g, ' $1')}</span><span className="font-semibold text-slate-800">{value}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500" style={{ width: `${value / max * 100}%` }}/></div></div>})}</div></section></div></div>;
}
