ALTER TABLE "PackageSnapshot" ADD COLUMN "currentRouteId" TEXT;
ALTER TABLE "PackageSnapshot" ADD COLUMN "currentTruckId" TEXT;
ALTER TYPE "PackageEventType" ADD VALUE 'PACKAGE_LOADED_TO_LAST_MILE';
ALTER TYPE "PackageEventType" ADD VALUE 'PACKAGE_REMOVED_FROM_LAST_MILE';
ALTER TYPE "HandheldAction" ADD VALUE 'LOAD_PACKAGE_TO_ROUTE';
ALTER TYPE "HandheldAction" ADD VALUE 'REMOVE_PACKAGE_FROM_ROUTE';
